### ISSUE TITLE
Wireguard is cross-platform

### ISSUE THREAD

**Issue by grr** [FGasper/p5-Linux-WireGuard#1]
From the homepage:
> Initially released for the Linux kernel, it is now cross-platform (Windows, macOS, BSD, iOS, Android)

Shouldn't the namespace be changed to reflect reality? Since it's a VPN, **Net::** would make sense.

**Comment by FGasper** [comment]
That's what I originally thought, but the embeddable library uses Netlink, which is Linux-specific.
